### ISSUE TITLE
Publish a release

### ISSUE THREAD

**Issue by jonkoops** [Amsterdam/use-promise#274]
I no longer have permission to publish a release. @alimpens @thomasm0 could you guys publish the new version from `main` by running `npm publish` or restore my permissions on NPM?

**Comment by alimpens** [comment]
When I pull the latest `main` and install, the lockfile is updated. That seems odd? Should I push the changes to the lockfile and publish to npm?

**Comment by jonkoops** [comment]
@alimpens Perhaps you are on an older version of NPM? Make sure that you are running the latest version of Node 16 and the included version of NPM.

**Comment by alimpens** [comment]
Done! Do you also want to be added to the @amsterdam organisation? Maybe a bit weird if you're not working for the gemeente

**Comment by jonkoops** [comment]
@alimpens Yeah sure you can add me, I was there before but I think I keep getting pruned as they think 'Hey this guy doesn't work for us'.

Marking this as closed.
